---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86150.
--- DateTime: 2025/1/6 19:40
---

local value = tonumber(redis.call("get", KEYS[1]))
local count = tonumber(ARGV[1])
if value + count > 0 then
    redis.call("set", KEYS[1], value + count)
    return 1
else
    return 0
end